#!/bin/sh

set -e

stats=/etc/bind/zones/named.stats

rm -f $stats
rndc stats
echo "<<<bind>>>"
grep -v '^\[' $stats | \
	grep -v '^---' | \
	grep -v '^+++' | \
	sed -e 's@^++ \(.*\) ++$@\1@' | \
	sed -e 's@^ *\([0-9]*\) \(.*\)$@\2 \1@g'
